version: "3.8" #Check docker engine version and match to docker compose version

services: 

#create container for application:Project 1
  project01-image: #name of image to be created
    #image:  pull image on docker hub 
    build: . #looking for dockerfile in local folder to build image
    ports:
      - 8081:8080  #Specify ports Host:container
    environment:  # specify environmental variables in container to be used
      - DB_URL
      - DB_USER
      - DB_PASS
    container_name: project01-container # name of container to be created
    depends_on: 
      - postgres
    volumes:
      - ../logs/app.log:/logs/application.log  #you mush create folder and file path or it will create the file as a folder (create file path in specified directory)


#create container for postgres
  postgres-image: #name of image to be created
    image: postgres #created image to be pulled from dockerhub
    ports: 
      - 5432:5432 #Specify ports Host:container
    environment: 
      - POSTGRES_PASSWORD=pass #password on host postgress
    container_name: postgres-container # name of container to be created
    volumes:
      - db-data:/var/lib/postgresql/data  #create local file to store data?
    depends_on:
      - postgres
    

#create container for loki
  loki-image:
    image: grafana/loki #created image to be pulled from dockerhub
    ports: 
      - 3100:3100
    container_name: loki-container # name of container to be created
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "https://<user_id>:<password>@logs-prod-us-central1.grafana.net/loki/api/v1/push"

#create continaer for grafana
  grafana-image:
    image: grafana/grafana
    ports: 
      - 3000:3000
    container_name: grafana-container
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki


volumes:
  db-data:
    driver: local
  grafana-storage:
    driver: local
